// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liydohmbwmhrrymntpua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpeWRvaG1id21ocnJ5bW50cHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTYzNzcsImV4cCI6MjA3MjU3MjM3N30.Su17vl8XlJXOl3Y7svcuUnf3SxHF95rJhFLPdRTTL1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});